// GENERATED by tools/rederive_ps_blank.py — do not edit by hand.
// Maps moduleNumber -> cellXf (left / center) in ps_weekly_blank.xlsx.
const psModuleXfLeftByNumber = <int, int>{
  1: 1293,
  2: 1295,
  3: 1297,
  4: 1299,
  5: 1301,
  6: 1303,
  7: 1305,
  8: 1307,
  9: 1309,
  10: 1311,
  11: 1313,
  12: 1315,
  15: 1317,
  16: 1319,
  17: 1321,
  50: 1323,
  51: 1325,
  53: 1327,
  54: 1329,
  -1: 1331, // fallback
};

const psModuleXfCenterByNumber = <int, int>{
  1: 1294,
  2: 1296,
  3: 1298,
  4: 1300,
  5: 1302,
  6: 1304,
  7: 1306,
  8: 1308,
  9: 1310,
  10: 1312,
  11: 1314,
  12: 1316,
  15: 1318,
  16: 1320,
  17: 1322,
  50: 1324,
  51: 1326,
  53: 1328,
  54: 1330,
  -1: 1332, // fallback
};

int psModuleXf(int moduleNumber) => psModuleXfLeft(moduleNumber);

int psModuleXfLeft(int moduleNumber) =>
    psModuleXfLeftByNumber[moduleNumber] ?? psModuleXfLeftByNumber[-1]!;

int psModuleXfCenter(int moduleNumber) =>
    psModuleXfCenterByNumber[moduleNumber] ?? psModuleXfCenterByNumber[-1]!;
