// GENERATED by tools/rebuild_ps_blank.py — do not edit by hand.
// Maps moduleNumber -> cellXf index in ps_weekly_blank.xlsx styles.
const psModuleXfByNumber = <int, int>{
  1: 1293,
  2: 1294,
  3: 1295,
  4: 1296,
  5: 1297,
  6: 1298,
  7: 1299,
  8: 1300,
  9: 1301,
  10: 1302,
  11: 1303,
  12: 1304,
  15: 1305,
  16: 1306,
  17: 1307,
  50: 1308,
  51: 1309,
  53: 1310,
  54: 1311,
  -1: 1312, // fallback
};

int psModuleXf(int moduleNumber) =>
    psModuleXfByNumber[moduleNumber] ?? psModuleXfByNumber[-1]!;
