"""Inject moduleColor cellXfs into blank + write Dart map. Compare to 66_PS.

Run AFTER tools/build_blank_openpyxl.py (once — refuses double inject).
"""
from __future__ import annotations

import re
import shutil
import zipfile
from pathlib import Path

from openpyxl import load_workbook

BLANK = Path(r"C:\Users\Gianmarco\corsi\assets\templates\ps_weekly_blank.xlsx")
SRC = Path(r"F:\66_PS 3° BTC B1 2025 EI+ CC - 2026.09.07.xlsx")
MAP_OUT = Path(r"C:\Users\Gianmarco\corsi\lib\services\ps_module_style_map.dart")

MODULE_ORDER = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 50, 51, 53, 54]
MODULE_PALETTE = [
    0xFF6366F1, 0xFF3B82F6, 0xFF06B6D4, 0xFF14B8A6, 0xFF22C55E,
    0xFF84CC16, 0xFFF59E0B, 0xFFF97316, 0xFFEF4444, 0xFFEC4899,
    0xFFA855F7, 0xFF8B5CF6, 0xFF0EA5E9, 0xFF10B981, 0xFFD97706,
    0xFF64748B, 0xFF78716C, 0xFF854D0E, 0xFF166534,
]
FALLBACK = 0xFF6B7280


def argb(c: int) -> str:
    return f"{c:08X}"


def inject(styles_xml: str) -> tuple[str, dict[int, int]]:
    if "corsi-module-xfs" in styles_xml:
        raise SystemExit(
            "styles already injected — re-run tools/build_blank_openpyxl.py first"
        )

    def count_attr(tag: str) -> int:
        m = re.search(rf'<{tag}[^>]*count="(\d+)"', styles_xml)
        return int(m.group(1)) if m else 0

    fill_count = count_attr("fills")
    font_count = count_attr("fonts")
    border_count = count_attr("borders")
    xf_count = count_attr("cellXfs")

    thin_border = (
        '<border><left style="thin"><color auto="1"/></left>'
        '<right style="thin"><color auto="1"/></right>'
        '<top style="thin"><color auto="1"/></top>'
        '<bottom style="thin"><color auto="1"/></bottom>'
        "<diagonal/></border>"
    )
    styles_xml = styles_xml.replace("</borders>", thin_border + "</borders>", 1)
    styles_xml = re.sub(
        r'(<borders[^>]*count=")(\d+)(")',
        rf"\g<1>{border_count + 1}\g<3>",
        styles_xml,
        count=1,
    )
    border_id = border_count

    white_font = (
        '<font><b/><sz val="9"/><color rgb="FFFFFFFF"/>'
        '<name val="Arial"/><family val="2"/></font>'
    )
    styles_xml = styles_xml.replace("</fonts>", white_font + "</fonts>", 1)
    styles_xml = re.sub(
        r'(<fonts[^>]*count=")(\d+)(")',
        rf"\g<1>{font_count + 1}\g<3>",
        styles_xml,
        count=1,
    )
    font_id = font_count

    colors = list(MODULE_PALETTE) + [FALLBACK]
    keys = list(MODULE_ORDER) + [-1]
    new_fills = []
    fill_ids = {}
    for i, col in enumerate(colors):
        fill_ids[keys[i]] = fill_count + i
        new_fills.append(
            f'<fill><patternFill patternType="solid">'
            f'<fgColor rgb="{argb(col)}"/><bgColor indexed="64"/>'
            f"</patternFill></fill>"
        )
    styles_xml = styles_xml.replace("</fills>", "".join(new_fills) + "</fills>", 1)
    styles_xml = re.sub(
        r'(<fills[^>]*count=")(\d+)(")',
        rf"\g<1>{fill_count + len(colors)}\g<3>",
        styles_xml,
        count=1,
    )

    xf_map = {}
    new_xfs = []
    for i, key in enumerate(keys):
        xf_map[key] = xf_count + i
        new_xfs.append(
            f'<xf numFmtId="0" fontId="{font_id}" fillId="{fill_ids[key]}" '
            f'borderId="{border_id}" xfId="0" applyFont="1" applyFill="1" '
            f'applyBorder="1" applyAlignment="1">'
            f'<alignment horizontal="center" vertical="center" wrapText="1"/>'
            f"</xf>"
        )
    styles_xml = styles_xml.replace(
        "</cellXfs>",
        "".join(new_xfs) + "</cellXfs><!-- corsi-module-xfs -->",
        1,
    )
    styles_xml = re.sub(
        r'(<cellXfs[^>]*count=")(\d+)(")',
        rf"\g<1>{xf_count + len(keys)}\g<3>",
        styles_xml,
        count=1,
    )
    return styles_xml, xf_map


def write_map(xf_map: dict[int, int]) -> None:
    lines = [
        "// GENERATED by tools/inject_module_styles.py — do not edit by hand.",
        "const psModuleXfByNumber = <int, int>{",
    ]
    for k in MODULE_ORDER:
        lines.append(f"  {k}: {xf_map[k]},")
    lines.append(f"  -1: {xf_map[-1]},")
    lines.append("};")
    lines.append("")
    lines.append("int psModuleXf(int moduleNumber) =>")
    lines.append("    psModuleXfByNumber[moduleNumber] ?? psModuleXfByNumber[-1]!;")
    lines.append("")
    MAP_OUT.write_text("\n".join(lines), encoding="utf-8")


def compare() -> None:
    def info(label, path, sheet=None):
        wb = load_workbook(path)
        ws = wb[sheet] if sheet else wb.active
        merges = set(str(m) for m in ws.merged_cells.ranges)
        print(f"{label}: size={path.stat().st_size} merges={len(merges)}")
        return merges

    m66 = info("66", SRC, "76S_09giugno_13giugno_EI")
    mb = info("blank", BLANK)
    print("merge overlap", len(m66 & mb), "/", len(m66))


def main() -> None:
    tmp = BLANK.with_suffix(".tmp.xlsx")
    with zipfile.ZipFile(BLANK, "r") as zin:
        styles = zin.read("xl/styles.xml").decode("utf-8")
        others = {n: zin.read(n) for n in zin.namelist() if n != "xl/styles.xml"}
    styles, xf_map = inject(styles)
    write_map(xf_map)
    with zipfile.ZipFile(tmp, "w", compression=zipfile.ZIP_DEFLATED) as zout:
        for n, data in others.items():
            zout.writestr(n, data)
        zout.writestr("xl/styles.xml", styles.encode("utf-8"))
    shutil.move(tmp, BLANK)
    print("injected", BLANK, "size", BLANK.stat().st_size, "mod15xf", xf_map[15])
    compare()


if __name__ == "__main__":
    main()
